;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Header File: BLIT.INC
;              Jaguar Blitter Equates
;
; NOTICE: This file has been incorporated into JAGUAR.INC. This file
;         is for compatibility reasons only.
;
	
	.include        "jaguar.inc"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; WARNING!!! The following EQU's exist here for compatibility only.
;;; Do not use them. There are more EQUs with better names in JAGUAR.INC
;;; These EQUs - Including this whole include file will go away in the next
;;; release
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

		IF      COMPAT

NOGO            EQU     $00000080       ; d07:     diagnostic

		ENDIF
