;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Header File: OBJLIST.INC
;              Jaguar Object List Equates
;
; NOTICE: The EQU's in this file have been mostly removed from Atari
;         include file updates. Those EQU's remaining have been moved
;         to JAGUAR.INC. This file is for compatibility reasons only.
;
        
        .include        "jaguar.inc"

